[project]
name = "pycon"
version = "0.1.0"
description = "Local Lab for AI and Python"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "llama-cpp-python==0.3.10",
    "streamlit>=1.46.1",
]
